name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1
      id: test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1
        setup-command: javac EquationSolution.java -encoding UTF8
        command: java -cp . EquationSolution
        input: '2 3 4

          '
        expected-output: 'Enter a, b, c: h is -3/4 k is 23/8'
        comparison-method: contains
        timeout: 10
    - name: test2
      id: test2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2
        setup-command: javac EquationSolution.java -encoding UTF8
        command: java -cp . EquationSolution
        input: '1 3 1

          '
        expected-output: 'Enter a, b, c: h is -3/2 k is -5/4'
        comparison-method: contains
        timeout: 10
    - name: test3
      id: test3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test3
        setup-command: javac EquationSolution.java -encoding UTF8
        command: java -cp . EquationSolution
        input: '5 5 5

          '
        expected-output: 'Enter a, b, c: h is -1/2 k is 15/4'
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
      with:
        runners: test1,test2,test3
